import { chapter, type Campaign, type Request } from "@/lib/tea-story";
import { formatVnd } from "@/lib/tea-shop";
import { ReportDialog } from "./DayReports";

export default function StoryPanels({ panel, request, campaign, day, cash, onClose, onDecision, onManage }: { panel: "intro" | "friends" | null; request: Request | null; campaign: Campaign; day: number; cash: number; onClose: () => void; onDecision: (allow: boolean) => void; onManage: () => void }) {
  if (request) return <ReportDialog title={`${request.name} muốn ${request.kind === "credit" ? "ghi nợ" : "mượn tiền"}`} onClose={() => onDecision(false)}><p className="story-copy">{request.kind === "credit" ? "Mình quên mang ví. Cho mình nợ ly hôm nay nhé?" : "Mình đang kẹt tiền. Bạn có thể giúp mình một chút không?"}</p><div className="story-rules"><b>{formatVnd(request.amount)} · nguy cơ quịt {request.risk}%</b><p>Hẹn trả sau {request.kind === "credit" ? 2 : 3} ngày. Đồng ý: thân thiện +8, có thể mất tiền. Từ chối: không mất tiền; 35% khách buồn, thân thiện −15 và nghỉ mua 3 ngày.</p></div><div className="pixel-report-actions"><button className="pixel-report-button" onClick={() => onDecision(false)}>Không cho</button><button className="pixel-report-button pixel-report-primary" disabled={request.kind === "loan" && cash <= request.amount} onClick={() => onDecision(true)}>Đồng ý</button></div></ReportDialog>;
  if (!panel) return null;
  const story = chapter(day);
  return <ReportDialog title={panel === "intro" ? story.title : "Khách quen & sổ nợ"} onClose={onClose}>
    {panel === "intro" ? <><p className="story-copy">{story.text}</p><div className="story-rules"><b>Ca 10 phút · tháng 30 ngày</b><p>Nguyên liệu: 38% tiền món đã bán. Vận hành: 25.000đ/ngày. Cuối tháng: thuê 300.000đ + thuế 5% tiền đã thu.</p><p>Đây là luật kinh tế trong game. Đồng hồ dừng khi mở popup hoặc nhập hàng. Có thể kết ca sớm.</p></div></> : <><p className="story-copy">Công nợ còn chờ: {formatVnd(campaign.debts.filter(d => d.status === "pending").reduce((n,d)=>n+d.amount,0))}</p><div className="story-list">{Object.values(campaign.friends).map(f => <div key={f.name}><b>{f.name} · ♡ {f.affinity}/100</b><small>{f.visits} lần ghé{f.blockedUntil > day ? ` · nghỉ mua đến ngày ${f.blockedUntil}` : ""}</small></div>)}{campaign.debts.map(d => <div key={d.id}><b>{d.name}: {formatVnd(d.amount)}</b><small>{d.kind === "loan" ? "Vay tiền" : "Nợ ly"} · hạn ngày {d.dueDay} · {d.status === "pending" ? "chờ trả" : d.status === "approved" ? "chờ giao món" : d.status === "paid" ? "đã trả" : "đã quịt"}</small></div>)}</div><details><summary>Nhật ký quyết định</summary>{campaign.log.map((line,i)=><p key={i} className="story-log">{line}</p>)}</details></>}
    {panel === "friends" && <button className="pixel-report-button story-continue" onClick={onManage}>Quản lý cửa hàng</button>}
    <button className="pixel-report-button story-continue" onClick={onClose}>{panel === "intro" ? "Mở cửa tiệm ♡" : "Trở lại quầy"}</button>
  </ReportDialog>;
}
